image: jekyll/jekyll

cache:
  paths:
    - _bundle/

build:
  stage: build
  script:
    - bundle install
    - bundle exec jekyll build
    - mv _site public
  artifacts:
    paths:
      - public
  except:
    - main

pages:
  stage: deploy
  script:
    - bundle exec jekyll build
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - main
