title = "Duckquill"
base_url = "https://duckquill.exozy.me"
description = "Modern, pretty, and clean theme"

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
build_search_index = false

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
accent_color = "#ff7800"
blog_title = "Writings of Duck's Feet"
blog_description = "Welcome to my quack'in blog, I quack about various stuff, but mostly I'm a demo"
date_format = "%d %B %Y"
hosting = "Codeberg"
issues_url = "https://codeberg.org/daudix-UFO/duckquill/issues"
source_url = "https://codeberg.org/daudix-UFO/duckquill"
nav_links = [
  {url = "https://codeberg.org/daudix-UFO/duckquill", name = "Repo"},
  {url = "/demo", name = "Demo"},
  {url = "/blog", name = "Blog"},
]

[extra.footer]
johnvert_ref = "daudix.exozy.me"
show_copyright = true
show_johnvert = false
show_powered_by = true
show_source = true

[extra.comments]
host = "mstdn.social"
user = "Daudix"
token = "jTNX9pAV8XEPBby0cPWF6CmGY60kkIy4vidggfxXmoQ"
