title = "Duckquill"
base_url = "https://daudix.codeberg.page/duckquill"
description = "Modern, pretty, and clean theme."

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
build_search_index = false
author = "Duck Quack"

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#ff7800"
# Same as primary_color, but with 20% opacity
primary_color_alpha = "rgba(255, 120, 0, 0.2)"
# Whether to use emoji as a favicon.
# Replace with an emoji wrapped in quotes.
emoji_favicon = false
# Whether the favicon is an animated GIF or not
animated_favicon = false
# Tera Date format used when listing posts
# (post publication date, tag posts list...).
# Not used in comments.
# See https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
date_format = "%d %B %Y"
# URL to website's issue tracker
issues_url = "https://codeberg.org/daudix/duckquill/issues"
# URL to website's source code
source_url = "https://codeberg.org/daudix/duckquill"
# Additional stylesheets; expects it to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
# stylesheets = [
#   "YOUR_STYLE.css",
#   "ALSO_YOUR_STYLE.css"
# ]

[extra.nav]
# Whether to show Atom/RSS feed button in the nav
show_feed = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
  {url = "@/blog/_index.md", name = "Blog"},
  {url = "@/demo/index.md", name = "Demo"},
  {url = "https://codeberg.org/daudix/duckquill", name = "Repo"},
]

[extra.footer]
# URL to the website without the https:// part,
# used for Johnvertisement leaderboard.
johnvert_ref = "daudix.codeberg.page"
# Whether to show "© Title, YEAR"
show_copyright = true
# Whether to show marketing via "john"
show_johnvert = false
# Whether to show "Powered by Zola and Duckquill"
show_powered_by = true
# Whether to show link to website source
show_source = true

# Based on https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Mastodon-powered commenting.
# Values can be overridden in front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; instance that you have an account on
host = "social.treehouse.systems"
# Your Mastodon username; used to determine who the original poster is
user = "daudix"
# Whether to show the QR code to Mastodon post
show_qr = true
# BCP 47 locale used for comment timestamps;
# See https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
locale = "en-IE"
