name = "Duckquill"
description = "Modern, pretty, and clean theme"
license = "MIT"
homepage = "https://codeberg.org/daudix/duckquill"
min_version = "0.17.2"
demo = "https://daudix.codeberg.page/duckquill"

[extra]
primary_color = "hsl(45 2% 60%)"
primary_color_alpha = "hsl(45 2% 60% / 20%)"
date_format = "%d %B %Y"
issues_url = ""
source_url = ""

[author]
name = "David Lapshin"
homepage = "https://daudix.codeberg.page"
